services:

  postgres:
    image: postgres:14.7-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
  
  django:
    build:
      context: .
    container_name: wait-web
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/wait-web
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_volume: