# Generated by Django 4.2 on 2023-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('placeholder', models.CharField(max_length=600, verbose_name='Placeholder')),
                ('image', models.ImageField(upload_to='static/images/', verbose_name='Image')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alternative text')),
                ('priority', models.IntegerField(default=1, verbose_name='Priority')),
            ],
        ),
    ]
