# Generated by Django 4.2 on 2023-04-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('label_en', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('label_ru', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('label_tt', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('placeholder', models.CharField(max_length=255, verbose_name='Placeholder')),
                ('placeholder_en', models.CharField(max_length=255, null=True, verbose_name='Placeholder')),
                ('placeholder_ru', models.CharField(max_length=255, null=True, verbose_name='Placeholder')),
                ('placeholder_tt', models.CharField(max_length=255, null=True, verbose_name='Placeholder')),
                ('image', models.ImageField(upload_to='static/images/carousel/', verbose_name='Image')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='ImageAlt')),
                ('priority', models.IntegerField(default=1, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'CarouselItem',
                'verbose_name_plural': 'CarouselItems',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category')),
                ('int_name', models.CharField(max_length=255, verbose_name='Category')),
                ('int_name_en', models.CharField(max_length=255, null=True, verbose_name='Category')),
                ('int_name_ru', models.CharField(max_length=255, null=True, verbose_name='Category')),
                ('int_name_tt', models.CharField(max_length=255, null=True, verbose_name='Category')),
                ('image', models.ImageField(upload_to='static/images/categories/', verbose_name='Image')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='ImageAlt')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Denomination')),
                ('int_name', models.CharField(max_length=255, verbose_name='Denomination')),
                ('int_name_en', models.CharField(max_length=255, null=True, verbose_name='Denomination')),
                ('int_name_ru', models.CharField(max_length=255, null=True, verbose_name='Denomination')),
                ('int_name_tt', models.CharField(max_length=255, null=True, verbose_name='Denomination')),
                ('description', models.TextField(max_length=600, verbose_name='Description')),
                ('description_en', models.TextField(max_length=600, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(max_length=600, null=True, verbose_name='Description')),
                ('description_tt', models.TextField(max_length=600, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('sold', models.BooleanField(default=False, verbose_name='Sold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CareatedAt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/products/', verbose_name='Image')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='ImageAlt')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
