# Generated by Django 4.2 on 2023-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
    ]
