# Generated by Django 4.2 on 2023-06-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carouselitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='text_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TextColor'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='placeholder_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='placeholder_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='placeholder_tt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder'),
        ),
    ]
