# Generated by Django 4.2 on 2023-07-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_carouselitem_text_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productfeature",
            options={
                "ordering": ["id"],
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
    ]
