# Generated by Django 4.2 on 2023-08-26 09:40

import os
from django.db import migrations


def fix_image_path_carouselitem(apps, schema_editor):
    CarouselItem = apps.get_model("app", "CarouselItem")
    for item in CarouselItem.objects.all():
        item.image = os.path.join("images", "carousel", os.path.basename(item.image.url))
        item.save()


def fix_image_path_category(apps, schema_editor):
    Category = apps.get_model("app", "Category")
    for category in Category.objects.all():
        category.image = os.path.join("images", "categories", os.path.basename(category.image.url))
        category.save()


def fix_image_path_productimage(apps, schema_editor):
    ProductImage = apps.get_model("app", "ProductImage")
    for image in ProductImage.objects.all():
        image.image = os.path.join("images", "products", os.path.basename(image.image.url))
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_carouselitem_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_image_path_carouselitem),
        migrations.RunPython(fix_image_path_category),
        migrations.RunPython(fix_image_path_productimage),
    ]
