# Generated by Django 4.2 on 2023-08-28 11:13

import app.models.home
import app.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230826_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.home.carouselitem_directory_path),
        ),
        migrations.AddField(
            model_name='category',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.product.category_directory_path),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.product.productimage_directory_path),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to=app.models.home.carouselitem_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=app.models.product.category_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=app.models.product.productimage_directory_path, verbose_name='Image'),
        ),
    ]
