# Generated by Django 4.2 on 2023-08-30 14:48

import app.models.home
import app.models.product
from django.db import migrations, models


def compute_image_size_and_save(apps, schema_editor):

    CarouselItem = apps.get_model("app", "CarouselItem")
    Category = apps.get_model("app", "Category")
    ProductImage = apps.get_model("app", "ProductImage")
    
    for item in CarouselItem.objects.all():
        item.save()
    for item in Category.objects.all():
        item.save()
    for item in ProductImage.objects.all():
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_carouselitem_image_webp_category_image_webp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to=app.models.home.carouselitem_directory_path, verbose_name='Image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to=app.models.product.category_directory_path, verbose_name='Image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to=app.models.product.productimage_directory_path, verbose_name='Image', width_field='image_width'),
        ),
        migrations.RunPython(compute_image_size_and_save)
    ]
