name: Deploy

on:
  push:
    branches:
      - main

jobs:
  lint_test:
    name: Lint & Test
    uses: ./.github/workflows/lint_test.yml
    secrets: inherit
  code_coverage:
    name: Code coverage
    uses: ./.github/workflows/code_coverage.yml
    needs: [lint_test]
    secrets: inherit
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [lint_test, code_coverage]
    timeout-minutes: 10
    steps:
      - name: Configure SSH
        env:
          SSH_HOST: ${{ secrets.VPS_IP }}
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_KEY: ${{ secrets.VPS_KEY }}
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/deploy.key
            chmod 600 ~/.ssh/deploy.key
            cat >>~/.ssh/config <<END
            Host deploy
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/deploy.key
              StrictHostKeyChecking no
            END
      - name: Stop app
        run: ssh deploy 'sudo systemctl stop gunicorn.socket'
      - name: Pull repo
        run: ssh deploy 'cd /var/www/production/wait-web/ && git pull'
      - name: Apply migrations
        run: ssh deploy 'cd /var/www/production/wait-web/ && make install && make migrate && make collectstatic'
      - name: Start app
        if: ${{ always() }}
        run: ssh deploy 'sudo systemctl stop gunicorn.socket'
