name: Deploy

on:
  push:
    branches:
      - main

jobs:
  lint_test:
    name: Lint & Test
    uses: ./.github/workflows/lint_test.yml
    secrets: inherit
  code_coverage:
    name: Code coverage
    uses: ./.github/workflows/code_coverage.yml
    secrets: inherit
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [lint_test, code_coverage]
    timeout-minutes: 10
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        env:
          PATH: ${{ secrets.VPS_PROJECT_PATH }}
          PASSWORD: ${{ secrets.VPS_PASSWORD }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          envs: PATH,PASSWORD
          script_stop: true
          script: |
            echo $PASSWORD | sudo -S systemctl stop gunicorn.socket
            cd $PATH
            git pull
            make install
            make migrate
            make collectstatic
            echo $PASSWORD | sudo -S systemctl start gunicorn.socket
            make collectstatic
            sudo systemctl start gunicorn.socket
